# Where things are
source              : .
destination         : ./_site

url: https://rynne.es/Rynne-Jekyll-Template


paginate: 5
paginate_path: "/blog/page:num/"

collections:
  posts:
    output          : true
    permalink       : /blog/:year/:month/:name
  pages:
    output          : true
    permalink       : /:name
  projects:
    output          : true

# Plugins
whitelist           : []
plugins             : 
  - jekyll-toc
  - jekyll-paginate

toc:
  max_level: 2 # default: 6

title: This is the site title
subtitle: The site subtitle!

main_nav:
- title: Home
  url: /
- title: About Me
  url: /about
- title: blog
  url: /blog
- title: Go to author's site
  url: http://rynne.es
  button: true
  icon: fas fa-envelope
  external: true
